"""Generate trade-study documents (directive §37) from simulations/results/*.json.

    PYTHONPATH=src python trade_studies/build_trade_docs.py

Decision method used in every trade (no arbitrary scoring):
  1. Screen candidates against hard requirements (pass/fail).
  2. Compare compliant candidates on quantified discriminators computed by the project models.
  3. Select the minimum-delivered-mass compliant candidate unless a discriminator with a quantified
     mission effect (value model, reliability, closure) justifies the mass difference; the
     justification is stated explicitly.
Weighted scoring appears only in TS-03, where weights are the expected work-content fractions of a
DRM-derived task catalogue (not preferences).
"""
from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "simulations" / "results"
OUT = ROOT / "trade_studies"
DISCL = ("> TSR-1 is an independent conceptual engineering study by Todaro Corp. References to NASA, ESA and other "
         "organizations are used solely as technical and architectural context.\n")


def J(n):
    return json.loads((RES / n).read_text())


def f(x, d=1):
    try:
        if isinstance(x, str):
            return x
        if x is None or (isinstance(x, float) and math.isnan(x)):
            return "—"
        return f"{x:.{d}f}"
    except Exception:
        return str(x)


def table(rows, cols, fmt=None):
    fmt = fmt or {}
    h = "| " + " | ".join(c[1] for c in cols) + " |\n|" + "---|" * len(cols) + "\n"
    for r in rows:
        h += "| " + " | ".join(fmt.get(c[0], lambda v: f(v) if isinstance(v, float) else str(v))(r[c[0]]) for c in cols) + " |\n"
    return h


def write(name, title, body):
    (OUT / name).write_text(f"# {title}\n\n{DISCL}\nGenerated by `trade_studies/build_trade_docs.py` from "
                            f"`simulations/results/`. Method: see `trade_studies/README.md`.\n\n{body}")
    print("wrote", name)


def main():
    T = J("trades.json")
    mob = J("mobility.json")
    rec = J("recovery.json")
    en = J("energy_power_thermal.json")
    val = J("value_model.json")
    base = J("baseline_summary.json")
    st = J("stability.json")

    # ------------------------------------------------------------------ TS-01 / TS-02
    m = T["mobility"]
    best = min(m, key=lambda r: r["delivered_mass_kg"])
    m2 = [r for r in m if r["suspension"] == "rocker_bogie_lowering"][0]
    body = "## TS-01 Mobility architecture\n\n**Hard requirements screened:** ground pressure ≤ 7 kPa (SR-MOB-01, S023), " \
           "mobility retained after one drive failure (SR-MOB-06), delivery ≤ 1.5 t goal (MR-11). Each candidate's wheels were " \
           "auto-sized to the same pressure and DP/W(40 %) ≥ 0.36 constraints at its own operational mass " \
           "(`trades/mobility_trades.size_wheel_for`), so differences are architectural, not wheel-size artefacts.\n\n"
    body += table(m, [("candidate", "Candidate"), ("delivered_mass_kg", "Delivered mass [kg]"),
                      ("mobility_mass_pred_kg", "Mobility+stab. mass [kg]"), ("wheel_D_m", "Wheel D [m]"),
                      ("wheel_b_m", "b [m]"), ("contact_pressure_kPa", "p [kPa]"),
                      ("max_slope_nom_deg", "Slope nom [°]"), ("max_slope_cons_deg", "Slope cons [°]"),
                      ("max_slope_one_wheel_out_deg", "1 drive out [°]"), ("max_slope_two_wheels_out_deg", "2 out [°]"),
                      ("obstacle_m", "Obstacle [m]"), ("mobility_actuators", "Actuators"),
                      ("p_mobility_retained_10yr", "P(mobile, 10 yr, no repair)")],
                   {"p_mobility_retained_10yr": lambda v: f(v, 2), "contact_pressure_kPa": lambda v: f(v, 2),
                    "wheel_D_m": lambda v: f(v, 2), "wheel_b_m": lambda v: f(v, 2)})
    body += f"""
**Findings.**
1. Slope capability is essentially identical across architectures (nominal ≈ {f(m2['max_slope_nom_deg'])}°,
   conservative ≈ {f(m2['max_slope_cons_deg'])}°): it is **traction-limited by the soil**, a ratio independent of gravity,
   so suspension sophistication does not buy gradeability.
2. Fully active six-leg and four-wheel active suspensions cost +80–100 kg over rocker-bogie for a larger obstacle
   capability (active-6) or fewer actuators (4-wheel) but **worse two-failure tolerance** for the four-wheeler
   ({f([r for r in m if r['n_wheels']==4][0]['max_slope_two_wheels_out_deg'])}° with two drives failed vs
   {f(m2['max_slope_two_wheels_out_deg'])}°).
3. Passive rocker-bogie is lightest ({f(best['delivered_mass_kg'],0)} kg delivered). Adding body lowering + differential
   lock costs {f(m2['delivered_mass_kg']-best['delivered_mass_kg'],0)} kg.

**Decision: M2 six-wheel rocker-bogie with body lowering and differential lock.** Justification for the
{f(m2['delivered_mass_kg']-best['delivered_mass_kg'],0)} kg over M1: (a) unloading any wheel for drive-ORU replacement
(self-serviceability, MR-13), (b) lowering the arm/crane bases 0.35 m for ground-level work (anchors, tow points),
(c) a sacrificial skid contact during winching. TS-04 shows the stability benefit alone is small — this is a
**descope candidate** recorded in the CDR.

**Rejected outright (qualitative):** tracks (metal tracks: dust ingress in many pin joints, mass; elastomer
tracks: vacuum/cold incompatible); legged walkers (ATHLETE-class: high power and actuator count for no
gradeability gain on a traction-limited surface).

## TS-02 Wheel architecture and sizing

Single-wheel sweep at operational mass {f(base['operational'],0)} kg (full grid in
`simulations/results/trade_wheel_sweep.csv`). Contact pressure self-regulates near 6–8 kPa (the soil pushes back as
the wheel sinks), so the 7 kPa rule effectively sets a minimum wheel width × diameter. The selected wheel
**Ø0.90 m × 0.40 m, 20 mm grousers** gives p = {f(mob['contact_pressure_kPa'],2)} kPa and sinkage
{f(mob['sinkage_m']*1000,0)} mm at the nominal wheel load {f(mob['wheel_load_N'],0)} N.

| Wheel type | TRL | Heritage | Dust | Fatigue | Model confidence | Selected |
|---|---|---|---|---|---|---|
""" + "".join(f"| {w['type']} | {w['trl']} | {w['heritage']} | {w['dust']} | {w['fatigue']} | {w['model_confidence']} | {'**yes**' if w['selected'] else 'no'} |\n" for w in T["wheel_types"]) + f"""
**Calibration note.** The model with Lunar Sourcebook Table 9.14 soil over-predicts the measured Apollo LRV
traverse energy (k_cal = {f(mob['k_cal'],2)}): either the in-situ soil is stronger than the trafficability set or flexible
wheels sink less. Energy estimates use k_cal; slope claims do **not** (they use the uncalibrated, conservative model).
"""
    write("mobility.md", "TS-01 Mobility architecture and TS-02 Wheel architecture", body)

    # ------------------------------------------------------------------ TS-03
    man = T["manipulators"]
    body = "Weights = expected fraction of TSR-1 manipulation work content per task, derived from the fault mix (A-09) and " \
           "DRM step content (`trades/manipulator_trades.TASKS`). Capability rules (`capability()`): 1 feasible, 0.75 with " \
           "fixture/crane work-around, 0.5 subset only, 0 infeasible.\n\n"
    body += table(man, [("architecture", "Architecture"), ("mass_kg", "Mass [kg]"), ("joints", "Actuated joints"),
                        ("weighted_coverage", "Weighted task coverage"), ("coverage_per_kg", "Coverage per kg"),
                        ("backup_after_primary_arm_failure", "Coverage after primary-arm failure"),
                        ("max_base_moment_Nm", "Max base moment [N·m]")],
                  {"weighted_coverage": lambda v: f(v, 3), "coverage_per_kg": lambda v: f(v, 4),
                   "backup_after_primary_arm_failure": lambda v: f(v, 2), "mass_kg": lambda v: f(v, 1),
                   "max_base_moment_Nm": lambda v: f(v, 0)})
    tasks = list(man[0]["per_task"].keys())
    body += "\n**Per-task capability matrix**\n\n| Task | " + " | ".join(a["architecture"].split(" ")[0] for a in man) + " |\n|---|" + "---|" * len(man) + "\n"
    for t in tasks:
        body += f"| {t} | " + " | ".join(f(a["per_task"][t], 2) for a in man) + " |\n"
    a3 = [a for a in man if a["architecture"].startswith("A3")][0]
    a4 = [a for a in man if a["architecture"].startswith("A4")][0]
    a7 = [a for a in man if a["architecture"].startswith("A7")][0]
    body += f"""
**Evaluation of the Todaro dual-asymmetric-arm hypothesis (directive §6A).** The heavy + dexterous pair (A3) is the
only architecture with full coverage, but costs {f(a3['mass_kg'],0)} kg — {f(a3['mass_kg']-a4['mass_kg'],0)} kg more than a
dexterous arm plus a cable-stayed crane boom (A4, coverage {f(a4['weighted_coverage'],2)}). In lunar gravity a heavy serial arm
carries its payload moment through every pitch joint (shoulder rating ≈ 1.5 kN·m for 150 kg at 2.3 m), while a
crane carries the load in tension/compression (LSMS principle, S015). **The heavy service arm is rejected.**

**Decision: A7 — two identical 7-DOF dexterous arms (20 kg rated, 1.6 m) + 150 kg crane boom.** Over A4 it adds
{f(a7['mass_kg']-a4['mass_kg'],0)} kg for (i) bimanual tasks without fixtures and (ii) removing the single most failure-prone
ORU as a single point of failure (λ = 0.08/yr → 55 % probability of an arm failure in 10 years; coverage after a
primary-arm failure 1.0 vs 0.0). The dual-arm idea therefore survives **in modified form** (identical dexterous arms,
crane instead of heavy arm). A4 is the recorded mass-descope fallback.

**Arm sizing basis:** torque at full horizontal extension in lunar gravity × dynamic factor 1.15 × motorisation factor
2 (L024), actuator mass from a torque-density MER (25 N·m/kg, ESTIMATE 15–40), Ti link tubes sized for 3 mm tip
deflection. Dexterous arm: {f(base['dex']['mass_kg'],1)} kg, shoulder rating {f(base['dex']['shoulder_rating_Nm'],0)} N·m.
Crane: {f(base['crane']['mass'],1)} kg, reach {f(base['crane']['reach'],2)} m.
"""
    write("manipulators.md", "TS-03 Manipulator architecture", body)

    # ------------------------------------------------------------------ TS-04 / TS-05
    so = T["stabilisation"]
    body = "## TS-04 Stabilisation\n\n" + table(so, [("option", "Option"), ("added_mass_kg", "Added mass [kg]"),
                                                     ("crane_side_capacity_15deg_kg", "Crane side-lift limit @2.56 m, 15° [kg]"),
                                                     ("winch_pull_limit_kN", "Planned winch pull limit [kN]"),
                                                     ("deploy_time_min", "Deploy time [min]")],
                                                {"crane_side_capacity_15deg_kg": lambda v: f(v, 0),
                                                 "winch_pull_limit_kN": lambda v: f(v, 2)})
    c7 = {c["case"][:3]: c for c in st["cases"]}
    body += f"""
**Findings.** For manipulation, locked wheels + differential lock already give tipping factor ≥ 1.5 at the crane's
150 kg rating on a 15° side slope (stability limit ≈ {f(so[0]['crane_side_capacity_15deg_kg'],0)} kg): **outriggers are not
needed** (+24 kg rejected). For winching, the vehicle's lunar weight (≈ {f(base['vehicle']['mass']*1.62/1000,2)} kN) is far below the
desired line pull: braked wheels alone limit planned pulls to ≈ {f(so[0]['winch_pull_limit_kN'],1)} kN; rear spades raise it to
≈ {f(so[3]['winch_pull_limit_kN'],1)} kN; spades + 2 helical anchors with front hold-down straps to ≈ {f(so[4]['winch_pull_limit_kN'],1)} kN.
A high fairlead (0.60 m) pitches the vehicle over at 4 kN (tipping factor < 1, case C7c); the **0.25 m fairlead** is a
design requirement.

**Decision:** locked wheels + differential lock for manipulation; rear spades + front helical anchors (S4/S5) for
recovery. Body lowering is retained for other reasons (TS-01).

## TS-05 Recovery architecture

Recovery envelope probability = fraction of {len(rec['p_env'])} architectures × sampled immobilisation cases (70 % small
rovers 50–500 kg, 30 % LTV-class 1–2.5 t; slope 0–20°; 40 % not embedded, 40 % partial 2–10 cm, 20 % deep 10–20 cm;
brake-release probability) recoverable with FoS 1.5, within the winch rating and tipping limit.

| Architecture | Added hardware [kg] | p_env (mid) | p_env (low resistance) | p_env (high resistance) | p_env (half-strength soil) |
|---|---|---|---|---|---|
""" + "".join(f"| {k} | {f(rec['restraint_mass'][k],1)} | {f(v['mid'],2)} | {f(v['low'],2)} | {f(v['high'],2)} | {f(v['weak_soil'],2)} |\n"
              for k, v in rec["p_env"].items()) + "\nWinch rating sweep (R4): " + ", ".join(
        f"{w['winch_kN']:.0f} kN → {w['p_env']:.2f}" for w in rec["winch_sweep"]) + "\n\n**Scenario results (directive §27)**\n\n" + table(
        rec["scenarios"], [("id", "ID"), ("title", "Scenario"), ("required_force_N", "Required force [N]"),
                           ("direct_tow_capacity_N", "Direct-tow capacity [N]"), ("method", "Method"),
                           ("margin", "Margin"), ("energy_Wh", "Energy [Wh]"), ("heat_W", "Heat [W]"),
                           ("hardpoint_load_N", "Hard-point load [N]"), ("feasible", "Feasible")],
        {"required_force_N": lambda v: f(v, 0), "direct_tow_capacity_N": lambda v: f(v, 0), "margin": lambda v: f(v, 2),
         "energy_Wh": lambda v: f(v, 1), "heat_W": lambda v: f(v, 0), "hardpoint_load_N": lambda v: f(v, 0)}) + """
**Findings.** Direct towing is useful only on near-level ground (Scenario A, D); on slopes the anchored winch is the
enabling element (B, B2, D2). Deep wheel embedding (C) is the hard case: feasible at the mid estimate with little
margin and infeasible at the upper-bound (Bekker compaction) estimate unless ramps are excavated first (C-dig) — which
justifies the regolith scoop tool. **Decision: R4 (4 kN winch, 50 m Vectran line, 2 rear spades, 2 helical anchors + 2
spare in MOD-REC).** R5 (4 anchors mounted) gains ≈ 0.02 in p_env and is not worth permanently carried hardware.
Physical caveat: anchor and spade capacities are first-principles estimates (no lunar data, technology gap TG-03).
"""
    write("stabilization.md", "TS-04 Stabilisation and TS-05 Recovery architecture", body)
    (OUT / "recovery.md").write_text("# TS-05 Recovery architecture\n\n" + DISCL +
                                     "\nTS-05 is documented together with TS-04 in [`stabilization.md`](stabilization.md) "
                                     "because the ground-reaction system serves both functions.\n")

    # ------------------------------------------------------------------ TS-06
    body = "## Energy architecture alternatives\n\n" + table(T["energy"], [("option", "Option"), ("added_mass_kg", "Added mass [kg]"),
                                                                        ("survival_dark_h", "Survival in darkness [h]"),
                                                                        ("survival_sunlit", "Survival in sunlight"),
                                                                        ("trl", "TRL"), ("issues", "Issues")],
                                                           {"added_mass_kg": lambda v: f(v, 1), "survival_dark_h": lambda v: f(v, 0) if not isinstance(v, str) else v})
    body += "\n## Battery size vs service radius (DRM-2 at the service edge + 50 h survival reserve)\n\n" + table(
        T["battery_vs_radius"], [("radius_km", "Radius [km]"), ("drm2_kwh", "DRM-2 [kWh]"),
                                 ("drm2_with_solar_kwh", "DRM-2 with PV [kWh]"), ("reserve_kwh", "Reserve [kWh]"),
                                 ("usable_eol_required_kwh", "Usable EOL required [kWh]"), ("pack_mass_kg", "Pack mass [kg]"),
                                 ("pack_mass_with_solar_kg", "Pack mass if PV credited [kg]")],
        {k: (lambda v: f(v, 2)) for k in ("drm2_kwh", "drm2_with_solar_kwh", "reserve_kwh", "usable_eol_required_kwh")} |
        {"pack_mass_kg": lambda v: f(v, 0), "pack_mass_with_solar_kg": lambda v: f(v, 0), "radius_km": lambda v: f(v, 1)})
    b = base["battery"]
    body += f"""
**Decision: Li-ion PPR battery {f(b['usable_eol_kwh'],0)} kWh usable at EOL ({f(b['nameplate_kwh'],1)} kWh nameplate,
{b['n_series']}s{b['n_parallel']}p, {f(b['mass'],0)} kg) + 1.5 m² fixed vertical PV + grid charging at ISPSIS nodes.**
Sized for DRM-2 at the 10 km service edge without PV credit. Vertical PV ({f(en['solar_avg_W'],0)} W average in sun) exceeds the
survival power ({f(en['survival_power_W'],0)} W): a TSR-1 stranded in sunlight survives indefinitely (closure ENERGY-3).
Full-battery survival in darkness: {f(en['survival_full_battery_h'],0)} h (≥ 120 h requirement, S030). Radioisotope power (E3)
is technically attractive (indefinite PSR operation, waste heat) but rejected for availability/approval reasons for an
independent programme; it is the recommended variant if a PSR-intensive mission is prioritised.

**Emergency power capability (directive §6C).** At the 10 km edge, after the outbound traverse and keeping return energy
and the reserve: {f(en['keepalive_duration_at_edge_h'],1)} h of 300 W keep-alive or {f(en['emergency_3kW_duration_at_edge_h'],1)} h at the full
3 kW rating. Longer support is provided by leaving a MOD-KA keep-alive module (TS-07). Cable: 25 m tether, 2 ×
{f(en['tether']['area_mm2'],1)} mm² Cu for 3 % drop at 3 kW ({f(en['tether']['loss_w'],0)} W loss). Charging 3 kW → 14 kWh in ≈ 6 h.

**Key sensitivity:** DRM energy is dominated by hotel loads during slow autonomous traverse, so **effective speed**
is the largest driver (tornado: 0.7 → 2.5 km/h changes DRM-2 energy by ≈ 2×) — faster verified autonomy saves more
battery than better motors.
"""
    write("power.md", "TS-06 Energy architecture", body)

    # ------------------------------------------------------------------ TS-07
    sm = T["service_modules"]
    ka = val["keepalive"]
    kt = val["keepalive_trade"]
    cap = json.loads((RES / "capacity_study.json").read_text())
    cap_den = {(c["n_assets"], c["mtbf_yr"], c["keepalive_modules"]): c["ka_denied"] for c in cap if c["n_tsr"] == 1}
    unsat = [c for c in cap if c["n_tsr"] == 1 and c["keepalive_modules"] == 8 and c["faults_per_yr_nominal"] <= 20]
    cap_park = sum(c["park_fraction"] for c in unsat) / len(unsat)
    cap_hold = sum(c["ka_hold_yr"] for c in unsat) / len(unsat)
    ka_opt_rows = {o["option"]: o for o in kt["options"]}
    kc4 = next(r for r in kt["value_trade"] if r["option"].startswith("KA-C") and r["n_modules"] == 4)
    kd4 = next(r for r in kt["value_trade"] if r["option"].startswith("KA-D") and r["n_modules"] == 4)
    body = table(sm["modules"], [("name", "Module"), ("mass_kg", "Mass [kg]"), ("function", "Function"),
                                 ("carry_fraction", "Fraction of sorties carrying it")],
                 {"mass_kg": lambda v: f(v, 1), "carry_fraction": lambda v: f(v, 2)})
    body += f"""
| Metric | Integrated (all kits always aboard) | Modular spine |
|---|---|---|
| Spine/interface overhead | 0 kg | {f(sm['spine_overhead_kg'],1)} kg |
| Mean carried kit mass per sortie | {f(sm['integrated_carried_kg'],1)} kg | {f(sm['modular_mean_carried_kg'],1)} kg (incl. overhead) |
| Deployable modules (MOD-KA left at assets) | impossible | yes |
| Reuse on other hosts (utility rover, LTV uncrewed mode) | no | yes, if host carries the slot standard |

**TS-07b — MOD-KA keep-alive module sizing (CDR-20).** A keep-alive module is left connected to a disabled asset
until its spare is fitted. It must supply the asset's survival power on average (two back-to-back vertical panels, one
face lit at a time) and bridge the longest dark period with its battery plus the asset's own thermal inertia. Asset
survival power (A-33, log-uniform 40–250 W), site illumination (A-34, 0.5–0.92) and dark-period length (A-35,
24–120 h) are sampled; the battery uses the TSR-1 pack rules (160 Wh/kg, DoD 0.8, 20 % fade, 28s strings).

""" + table(kt["options"], [("option", "Option"), ("battery_kg", "Battery [kg]"), ("pv_kg", "PV [kg]"),
                            ("mass_kg", "Module mass incl. 20 % MGA [kg]"), ("p_sustained_nominal_w", "Sustained output, nominal site [W]"),
                            ("bridge_nominal_h", "Battery bridging at 100 W [h]"), ("p_sustain", "P(sustains asset)"),
                            ("p_sustain_low", "P, assets ×1.5 power"), ("p_sustain_high", "P, assets ×0.67 power")],
            {"battery_kg": lambda v: f(v, 1), "pv_kg": lambda v: f(v, 1), "mass_kg": lambda v: f(v, 1),
             "p_sustained_nominal_w": lambda v: f(v, 0), "bridge_nominal_h": lambda v: f(v, 0),
             "p_sustain": lambda v: f(v, 2), "p_sustain_low": lambda v: f(v, 2), "p_sustain_high": lambda v: f(v, 2)}) + f"""
The pre-CDR placeholder (2 kWh, 0.75 m², **23 kg**) was physically inconsistent: 2 kWh usable at end of life needs
≈ 20 kg of cells alone, and that module sustains only ≈ 40 % of plausible parked assets.

**Option × inventory value trade** ({val['base_scenario']['n_assets']} assets, 10 yr, sampled uncertainty; net = Earth mass avoided − inventory mass):

| Option | Modules | P(sustain) | ΔA [pp] | Preventable losses (TSR) | Mass avoided [kg] | Net after inventory [kg] | Requests with no module free |
|---|---|---|---|---|---|---|---|
""" + "".join(f"| {r['option']} | {r['n_modules']} | {r['p_sustain']:.2f} | {100*r['dA_mean']:.1f} | {r['plost1_mean']:.1f} | "
              f"{r['mass_avoided_mean']:.0f} | {r['net_after_inventory']:.0f} | {r['ka_denied_mean']:.2f} |\n"
              for r in kt["value_trade"]) + f"""
**Inventory sweep with the selected module ({kt['selected']}, {val['keepalive_module_kg']:.1f} kg):**

| MOD-KA count | Inventory mass [kg] | ΔA [pp] | Preventable losses (TSR) | Earth mass with TSR-1 [kg] | Requests with no module free |
|---|---|---|---|---|---|
""" + "".join(f"| {k['keepalive_modules']} | {k['inventory_mass_kg']:.0f} | {100*k['dA_mean']:.1f} | {k['plost1_mean']:.1f} | "
              f"{k['mass1_mean']:.0f} | {k['ka_denied_mean']:.2f} |\n" for k in ka) + f"""
Keep-alive modules buy **losses and logistics mass, not availability**: a parked asset is still down while it waits
for its spare, so ΔA is flat (or slightly lower, because a lost asset returns as a new replacement while a parked one
waits for a spare and, for L0/L1, for crew), whereas preventable losses and Earth-supplied mass fall steeply until
the inventory stops being exhausted.

**Inventory rule (CDR-19).** By Little's law the mean number of modules deployed is
L = f_park · p_KA · F · T_hold, with F the fault rate, f_park ≈ {cap_park:.2f} the fraction of faults that leave a
stabilised but unrepaired asset (capacity study), p_KA = {kt['selected_row']['p_sustain']:.2f} and T_hold ≈ {cap_hold:.1f} yr the mean
deployment time (longer than the 0.5 yr spare lead time because L0/L1 assets wait for crew). The inventory is the
Poisson 95th percentile of L (`value_model.keepalive_inventory`). For base sizing the fault rate is the expected value
over the MTBF prior, F = N · E[1/MTBF] (`keepalive_inventory_for_base`): """ + ", ".join(f"{s_['n_assets']} assets → {s_['keepalive_modules']}" for s_ in val['asset_sweep']) + f""".
The capacity study (nominal scenarios, fixed MTBF) checks the rule against simulated keep-alive demand:

| Assets | MTBF [yr] | Fault rate [1/yr] | Rule (q95) | Requests with no module free over 10 yr: 2 / 4 / 8 modules |
|---|---|---|---|---|
""" + "".join(f"| {c['n_assets']} | {c['mtbf_yr']} | {c['faults_per_yr_nominal']:.1f} | {c['ka_rule_q95']} | "
              f"{cap_den[(c['n_assets'], c['mtbf_yr'], 2)]:.1f} / {cap_den[(c['n_assets'], c['mtbf_yr'], 4)]:.1f} / "
              f"{cap_den[(c['n_assets'], c['mtbf_yr'], 8)]:.1f} |\n" for c in cap if c['n_tsr'] == 1 and c['keepalive_modules'] == 4) + f"""
**Decision: modular service spine (6 slots); MOD-KA = {kt['selected']} ({val['keepalive_module_kg']:.0f} kg); inventory
{val['base_scenario']['keepalive_modules']} modules at the {val['base_scenario']['n_assets']}-asset reference base, scaled with the rule; at most two carried at once
(2 × {val['keepalive_module_kg']:.0f} kg ≤ 150 kg spine).** KA-D gives a slightly larger net benefit at four modules
({kd4['net_after_inventory'] - kc4['net_after_inventory']:+.0f} kg, {100 * (kd4['net_after_inventory'] / kc4['net_after_inventory'] - 1):+.0f} %) but each module is
{ka_opt_rows['KA-D 1.5 m² / 6 kWh']['mass_kg']:.0f} kg, so only one fits the spine with ORUs. Modularity is justified
functionally (deployable keep-alive, host portability), not by mass alone. **Fluid servicing is not
baselined**: no fluid-serviceable asset class was identified in the Moon Base architecture context; it remains an
optional future module.
"""
    write("service_modules.md", "TS-07 Service-module architecture", body)

    # ------------------------------------------------------------------ TS-08
    c = T["comms"]
    body = f"""| Option | Link availability |
|---|---|
""" + "".join(f"| {k} | {v:.3f} |\n" for k, v in c["availability"].items()) + f"""
Assumed component availabilities: surface network 0.90 within the base, relay 0.80 (early constellation), DTE 0.51
(S073). Link budget (S-band 2.25 GHz, 5 W RF, 10 dBi, relay G/T 0 dB/K, 3 dB losses, Eb/N0 4 dB + 3 dB margin):

| Case | EIRP [dBW] | FSPL [dB] | C/N0 [dB-Hz] | Max data rate |
|---|---|---|---|---|
| relay @ 10 000 km | {f(c['link_10000km']['eirp_dbw'])} | {f(c['link_10000km']['fspl_db'])} | {f(c['link_10000km']['cn0_dbhz'])} | {c['link_10000km']['max_rate_bps']/1e3:.0f} kbit/s |
| relay @ 3 000 km | {f(c['link_3000km']['eirp_dbw'])} | {f(c['link_3000km']['fspl_db'])} | {f(c['link_3000km']['cn0_dbhz'])} | {c['link_3000km']['max_rate_bps']/1e6:.1f} Mbit/s |
| Ka-band option @ 10 000 km (10 W, 30 dBi, G/T 10) | {f(c['ka_band_10000km']['eirp_dbw'])} | {f(c['ka_band_10000km']['fspl_db'])} | {f(c['ka_band_10000km']['cn0_dbhz'])} | {c['ka_band_10000km']['max_rate_bps']/1e6:.1f} Mbit/s |

A DRM's approval-critical data (~50 MB of imagery/LiDAR per hold point set) moves over S-band relay in ≈ 15–20 min
worst case; bulk data waits for the surface network (DTN store-and-forward). **Decision: surface network + LunaNet
S-band relay + UHF mesh + DTN** (availability ≈ {c['availability']['C4 surface network + relay + mesh + DTN (selected)']:.2f}); Ka-band
rejected (pointing mechanism in dust, power) because approval latency, not bandwidth, limits productivity; a
deployable repeater module (MOD-RPT) covers PSR excursions.
"""
    write("communications.md", "TS-08 Communications architecture", body)

    # ------------------------------------------------------------------ TS-09
    body = table(T["autonomy"], [("option", "Option"), ("task_h", "ORU-swap duration [h]"),
                                 ("operator_h", "Human operator time [h]"), ("works_in_outage", "Works in comm outage"),
                                 ("contact_safety", "Contact safety")],
                 {"task_h": lambda v: f(v, 1), "operator_h": lambda v: f(v, 1)})
    body += """
Model (`trades/other_trades.autonomy_task_time`): teleoperation = 300 discrete motions × (8 s round-trip incl.
processing + 10 s operator decision + 15 s motion) / DTE availability 0.51; supervised autonomy = 2 h execution +
8 hold-point approvals × 10 min.

**Decision: AU3 supervised autonomy** — verified skills executed onboard with local force/torque loops, a
deterministic safety layer, and human approval at irreversible steps. Earth teleoperation is retained only as a
low-rate "point-and-go" contingency; local crew teleoperation is a backup when crew are present. Full autonomy (AU4)
is rejected because novel-fault handling cannot be verified to the level required near crew and high-value assets.

**AI/ML components (directive §21):**

| Component | Why deterministic software is insufficient | Training/data | Verification boundary | Confidence handling | Fallback |
|---|---|---|---|---|---|
| Terrain classification (soft soil, rocks) | appearance-based hazards under extreme lighting are hard to hand-code | analogue-site + lunar imagery (VIPER/CADRE/Chang'e), simulated long-shadow renders | output is a cost map consumed by a geometric planner with hard LiDAR obstacle limits | per-cell uncertainty → slow down / stop | geometric-only planning at reduced speed |
| Visual anomaly detection (cracks, dust, connector damage) | open-ended anomaly appearance | asset-owner reference imagery + synthetic defects | advisory: flags for human review; never triggers an irreversible action | score + calibrated threshold | human inspection of imagery |
| Pose estimation for docking/connector mating | robust under specular, low-sun conditions | fiducial + CAD-based synthetic training | must agree with fiducial/LiDAR pose within tolerance before contact | disagreement → abort to stand-off | fiducial-only pose |
| Fault diagnosis ranking | combinatorial fault trees of heterogeneous assets | asset FMEA/telemetry models | ranks hypotheses; tests are deterministic electrical measurements | top-k with probabilities | operator-selected diagnosis |
| Task-plan proposal (LLM/planner hybrid) | natural-language asset manuals, novel combinations | asset documentation | output must compile to the verified-skill grammar and pass a deterministic plan checker | rejected plans returned to humans | DRM templates |
"""
    write("autonomy.md", "TS-09 Autonomy architecture", body)

    # ------------------------------------------------------------------ TS-10
    body = "## Chassis face material (structures.chassis model)\n\n" + table(
        T["chassis_materials"], [("material", "Material"), ("chassis_mass_kg", "Chassis mass [kg]"),
                                 ("t_face_mm", "Equivalent wall [mm]"), ("f1_Hz", "f₁ [Hz]"), ("cte_per_K", "CTE [1/K]")],
        {"chassis_mass_kg": lambda v: f(v, 1), "t_face_mm": lambda v: f(v, 2), "f1_Hz": lambda v: f(v, 0),
         "cte_per_K": lambda v: f"{v:.1e}"})
    body += "\n## Arm link material (manipulation.arm model, 20 kg / 1.6 m arm)\n\n" + table(
        T["arm_materials"], [("material", "Material"), ("arm_mass_kg", "Arm mass [kg]"), ("link_mass_kg", "Link mass [kg]"),
                             ("specific_stiffness_MNm_per_kg", "E/ρ [MN·m/kg]"),
                             ("thermal_growth_mm_1p5m_250K", "Growth over 1.5 m, 250 K [mm]")],
        {"arm_mass_kg": lambda v: f(v, 1), "link_mass_kg": lambda v: f(v, 2), "specific_stiffness_MNm_per_kg": lambda v: f(v, 1),
         "thermal_growth_mm_1p5m_250K": lambda v: f(v, 2)})
    body += """
**Findings.** Both the chassis (minimum-gauge driven) and the arms (actuator-mass dominated) are insensitive to
structural material choice: CFRP saves ≈ 15 kg on the chassis and ≈ 1–2 kg per arm. Selection therefore rests on
durability across ~3650 thermal cycles between ≈ 40 K and 390 K, conductive heat spreading in the WEB, impact and
abrasion tolerance, CTE compatibility at joints, and heritage. **Selected:** Al 7075-T7351/Al 5056 honeycomb
chassis with Ti-6Al-4V hard points; Ti-6Al-4V dexterous-arm links; CFRP only for the long, buckling-critical crane boom
and the mast. The full matrix (40 application/candidate rows incl. gears, bearings, lubricants, seals, cables,
connectors, fasteners, insulation, radiators, tool heads) is `engineering/materials_matrix.csv`.
"""
    write("materials.md", "TS-10 Structural materials", body)

    idx = """# Trade studies — index and method

""" + DISCL + """
| ID | Trade | File | Decision |
|---|---|---|---|
| TS-01 | Mobility architecture | [mobility.md](mobility.md) | 6-wheel rocker-bogie + body lowering + differential lock |
| TS-02 | Wheel architecture/sizing | [mobility.md](mobility.md) | rigid Ti-6Al-4V Ø0.90 × 0.40 m, 20 mm grousers |
| TS-03 | Manipulator architecture | [manipulators.md](manipulators.md) | 2 identical 7-DOF dexterous arms + 150 kg crane boom (heavy arm rejected) |
| TS-04 | Stabilisation | [stabilization.md](stabilization.md) | locked wheels + diff lock (manipulation); spades + helical anchors (winching); no outriggers |
| TS-05 | Recovery | [stabilization.md](stabilization.md) | 4 kN anchored winch, 0.25 m fairlead, 2 spades, 2 (+2) helical anchors |
| TS-06 | Energy | [power.md](power.md) | 14 kWh EOL Li-ion + 1.5 m² vertical PV + ISPSIS grid charging; RPS rejected |
| TS-07 | Service modules | [service_modules.md](service_modules.md) | modular 6-slot spine; 2 keep-alive modules; no fluid module |
| TS-08 | Communications | [communications.md](communications.md) | surface network + LunaNet S-band relay + mesh + DTN |
| TS-09 | Autonomy | [autonomy.md](autonomy.md) | supervised autonomy with deterministic safety layer |
| TS-10 | Structural materials | [materials.md](materials.md) | Al honeycomb chassis, Ti arm links/fittings, CFRP boom/mast |

**Method (no arbitrary scoring).** (1) Screen against hard requirements; (2) compare compliant options on discriminators
computed by the project models; (3) choose minimum delivered mass unless a quantified mission effect (value model,
reliability, closure check) justifies more, stating the justification. Weighted scoring is used only in TS-03, with
weights equal to DRM-derived work-content fractions.
"""
    (OUT / "README.md").write_text(idx)


if __name__ == "__main__":
    main()
