"""Generate paper/references.bib from research/source_register.csv.

    python paper/build_bib.py

One entry per source; the key is the register ID (S001 ...). No DOI, page or volume information is added beyond
what the register records: identifiers and URLs are copied verbatim and every entry carries the register's
verification label in its ``note`` field (EXCERPT, LITERATURE-RECALL, SECONDARY, EXISTENCE-ONLY, NOT-RETRIEVED).
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TYPE_MAP = (("conference", "inproceedings"), ("journal", "article"), ("paper", "article"), ("thesis", "phdthesis"),
            ("book", "book"), ("handbook", "book"), ("standard", "techreport"), ("special publication", "techreport"),
            ("technical", "techreport"), ("report", "techreport"), ("memorandum", "techreport"))


def bibtype(doc_type: str) -> str:
    t = doc_type.lower()
    for k, v in TYPE_MAP:
        if k in t:
            return v
    return "misc"


def esc(s: str) -> str:
    s = s.replace("\\", "").replace("{", "(").replace("}", ")")
    s = re.sub(r"([&%#_$])", r"\\\1", s)
    return s


def entries() -> list[dict]:
    with open(ROOT / "research" / "source_register.csv", newline="") as f:
        return list(csv.DictReader(f))


def main() -> None:
    out = ["% references.bib — generated by paper/build_bib.py from research/source_register.csv. Do not edit by hand.",
           "% Each note records how the source was accessed in this study (see research/source_register.csv).", ""]
    for r in entries():
        typ = bibtype(r["document_type"])
        year = re.search(r"\d{4}", r["year"] or "")
        fields = [("title", "{" + esc(r["title"]) + "}"), ("author", "{{" + esc(r["authors_or_org"]) + "}}")]  # literal author list
        if year:
            fields.append(("year", year.group(0)))
        fields.append(("howpublished", esc(r["identifier_or_url"])))
        fields.append(("note", f"{esc(r['document_type'])}; access: {esc(r['verification'])}; used for: {esc(r['used_for'])}"))
        if typ == "inproceedings":
            fields.append(("booktitle", esc(r["authors_or_org"])))
        if typ == "techreport":
            fields.append(("institution", esc(r["authors_or_org"])))
        if typ == "article":
            fields.append(("journal", esc(r["document_type"])))
        body = ",\n".join(f"  {k} = {{{v}}}" if not v.startswith("{") else f"  {k} = {v}" for k, v in fields)
        out.append(f"@{typ}{{{r['source_id']},\n{body}\n}}\n")
    (ROOT / "paper" / "references.bib").write_text("\n".join(out))
    print(f"references.bib: {len(entries())} entries")


if __name__ == "__main__":
    main()
